import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import confetti from "canvas-confetti";
import "../app.css";
import {
  ArrowRight, BarChart3, BookOpen, Check, CheckCircle2, ChevronLeft, Clock3,
  Copy, Flame, Home, LayoutGrid, Lightbulb, LogOut, Menu, MessageCircle,
  MoreHorizontal, Plus, RotateCcw, Search, Settings, Sparkles, Target, Trash2,
  Trophy, X, Zap,
} from "lucide-react";

type Deadline = "1 semana" | "1 mês" | "3 meses" | "6 meses" | "1 ano";
type Status = "Em andamento" | "Pausado" | "Concluído";
type Stage = { id:string; label:string; period:string; objective:string; why:string; plan:string[]; exercise:string; mission:string; indicator:string; next:string; done:boolean };
type Log = { date:string; stage:string; mission:string; result:"concluída"|"não concluída"; note:string };
type Project = { id:string; title:string; description:string; createdAt:string; deadline:Deadline; status:Status; currentStage:number; answers:Record<string,string>; stages:Stage[]; logs:Log[]; lastActivity:string };
type Store = { user:{name:string;password:string}|null; projects:Project[] };
const KEY="projeto-de-vida-v2";
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>Math.random().toString(36).slice(2,10);
const blank:Store={user:null,projects:[]};
const load=():Store=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")||blank}catch{return blank}};
const save=(s:Store)=>localStorage.setItem(KEY,JSON.stringify(s));
const areas=["RESULTADO","MOTIVAÇÃO","SITUAÇÃO ATUAL","OBSTÁCULOS","COMPROMISSO"];
const deadlines:Deadline[]=["1 semana","1 mês","3 meses","6 meses","1 ano"];
const contextOf=(g:string)=>{const x=g.toLowerCase();if(/negócio|empresa|cliente|venda|empreend/.test(x))return"negócio";if(/inglês|idioma|aprender|estudo|curso/.test(x))return"aprendizado";if(/dinheiro|finance|dívida|econom/.test(x))return"vida financeira";if(/treino|saúde|peso|corrida|academia/.test(x))return"saúde e rotina";if(/livro|escrever|conteúdo/.test(x))return"projeto criativo";return"objetivo"};
function questions(goal:string){const c=contextOf(goal);return[
 `Resultado — O que exatamente precisa acontecer para você considerar ${c} realizado? Descreva um resultado observável.`,
 `Motivação — Por que realizar ${c} é importante para você neste momento? O que muda quando isso acontece?`,
 `Situação atual — Onde você está hoje em relação a ${c}? O que já existe, o que falta e quais recursos você possui?`,
 `Obstáculos — O que pode impedir, atrasar ou dificultar ${c}? Pense em tempo, dinheiro, conhecimento, ambiente e padrões que você repete.`,
 `Compromisso — O que você está disposto a fazer consistentemente para chegar lá? Qual esforço é realista para sua rotina?`];}
function periods(d:Deadline){if(d==="1 semana")return Array.from({length:7},(_,i)=>`Dia ${i+1}`);if(d==="1 mês")return ["Semana 1","Semana 2","Semana 3","Semana 4"];if(d==="3 meses")return ["Mês 1","Mês 2","Mês 3"];if(d==="6 meses")return Array.from({length:6},(_,i)=>`Mês ${i+1}`);return Array.from({length:12},(_,i)=>`Mês ${i+1}`)}
function makeStages(title:string,description:string,answers:Record<string,string>,deadline:Deadline):Stage[]{const ps=periods(deadline);const motivation=answers["MOTIVAÇÃO"]||"seu motivo central";const obstacle=answers["OBSTÁCULOS"]||"os obstáculos identificados";return ps.map((p,i)=>({id:uid(),label:p,period:p,objective:i===0?`Estabelecer a primeira evidência concreta de avanço em ${title}.`:`Avançar um nível em direção a ${title}, usando o que foi aprendido na etapa anterior.`,why:`Esta etapa conecta a intenção ao comportamento. Ela existe para transformar ${title} em uma sequência observável, sem tentar resolver tudo de uma vez. O motivo declarado — ${motivation.slice(0,120)} — serve como critério de prioridade.`,plan:[`Revise o resultado desejado e escolha a menor ação que produz evidência.`,`Reserve um bloco de tempo compatível com seu compromisso.`,`Execute a ação e registre o resultado, incluindo o que dificultou ou facilitou.`,`Ajuste o próximo passo com base no que realmente aconteceu.`],exercise:i%2===0?`Escreva três evidências que mostrariam que você está mais perto de ${title}. Escolha uma para produzir nesta etapa.`:`Faça uma revisão de 10 minutos: o que funcionou, o que travou e qual decisão concreta evita repetir o obstáculo “${obstacle.slice(0,90)}”?`,mission:i===0?`Defina por escrito a primeira ação de ${title}, reserve horário para ela e execute até o fim desta etapa.`:`Escolha uma ação mensurável que aproxime ${title} do resultado e registre a evidência de conclusão.`,indicator:`Existe uma evidência registrada de que a ação foi executada e o próximo passo está definido.`,next:i<ps.length-1?`Use o resultado desta etapa para entrar em ${ps[i+1]}. Não carregue pendências sem decidir o que fazer com elas.`:"Revise todo o caminho, consolide aprendizados e avalie se o resultado definido foi alcançado.",done:false}));}
function buildProject(title:string,description:string,answers:Record<string,string>,deadline:Deadline):Project{return{id:uid(),title,description,createdAt:today(),deadline,status:"Em andamento",currentStage:0,answers,stages:makeStages(title,description,answers,deadline),logs:[],lastActivity:today()}}
function progress(p:Project){return Math.round(p.stages.filter(s=>s.done).length/p.stages.length*100)}

export const Route=createFileRoute("/")({component:Index});
function Index(){
 const [store,setStore]=useState<Store>(load);const [view,setView]=useState("home");const [active,setActive]=useState<string|null>(null);const [mobile,setMobile]=useState(false);
 const [login,setLogin]=useState(false);const [name,setName]=useState("");const [password,setPassword]=useState("");
 const [wizard,setWizard]=useState(1);const [goal,setGoal]=useState("");const [desc,setDesc]=useState("");const [answers,setAnswers]=useState<Record<string,string>>({});const [deadline,setDeadline]=useState<Deadline>("3 meses");
 const [query,setQuery]=useState("");const [filter,setFilter]=useState<"Todos"|Status>("Todos");const [mentor,setMentor]=useState("");const [reply,setReply]=useState("");const [openStage,setOpenStage]=useState(0);
 useEffect(()=>save(store),[store]);
 const project=store.projects.find(p=>p.id===active)||null;
 const completed=store.projects.reduce((n,p)=>n+p.stages.filter(s=>s.done).length,0);
 const setStoreSafe=(s:Store)=>{setStore(s);save(s)};
 const nav=(v:string)=>{setView(v);setMobile(false);if(v!=="project")setActive(null)};
 const newGoal=()=>{setWizard(1);setGoal("");setDesc("");setAnswers({});setDeadline("3 meses");nav("new")};
 const create=()=>{const p=buildProject(goal.trim(),desc.trim(),answers,deadline);setStoreSafe({...store,projects:[...store.projects,p]});setActive(p.id);setView("project");setOpenStage(0)};
 const open=(p:Project)=>{setActive(p.id);setView("project");setOpenStage(Math.min(p.currentStage,p.stages.length-1))};
 const toggleStage=()=>{if(!project)return;const idx=openStage;const nextDone=!project.stages[idx].done;const stages=project.stages.map((s,i)=>i===idx?{...s,done:nextDone}:s);const cp=Math.min(stages.findIndex(s=>!s.done)<0?stages.length-1:stages.findIndex(s=>!s.done),stages.length-1);const done=stages.every(s=>s.done);const log:Log={date:today(),stage:stages[idx].label,mission:stages[idx].mission,result:nextDone?"concluída":"não concluída",note:"Atualização registrada pelo usuário."};const np={...project,stages,currentStage:cp,status:done?"Concluído" as Status:"Em andamento" as Status,lastActivity:today(),logs:[...project.logs,log]};setStoreSafe({...store,projects:store.projects.map(p=>p.id===project.id?np:p)});if(done&&nextDone)confetti({particleCount:180,spread:100,origin:{y:.6}})};
 const duplicate=()=>{if(!project)return;const copy:Project={...project,id:uid(),title:`${project.title} — nova jornada`,createdAt:today(),status:"Em andamento",currentStage:0,stages:project.stages.map(s=>({...s,id:uid(),done:false})),logs:[],lastActivity:today()};setStoreSafe({...store,projects:[...store.projects,copy]});open(copy)};
 const remove=()=>{if(!project)return;if(confirm(`${store.user?.name||"Você"}, este projeto e seu histórico serão apagados. Essa ação não poderá ser desfeita. Deseja realmente excluir?`)){setStoreSafe({...store,projects:store.projects.filter(p=>p.id!==project.id)});nav("projects")}};
 const mentorAsk=()=>{if(!mentor.trim())return;const p=project;const c=p?`No projeto “${p.title}”, na etapa “${p.stages[p.currentStage]?.label}”, `:"Neste momento, ";let r="";const q=mentor.toLowerCase();if(q.includes("atras")||q.includes("tempo"))r=`${c}não tente recuperar tudo de uma vez. Retome a missão da etapa atual, reduza o escopo se necessário e registre uma nova evidência de execução hoje.`;else if(q.includes("desist")||q.includes("difícil"))r=`${c}volte ao motivo que você registrou, separe o que está sob seu controle e transforme o obstáculo em uma ação de até 30 minutos. A meta agora é recuperar movimento, não resolver o projeto inteiro.`;else if(q.includes("prior")||q.includes("próxima"))r=`${c}a prioridade é a missão: “${p?.stages[p.currentStage]?.mission||"definir a próxima ação"}”. Execute, registre o resultado e só então escolha o próximo passo.`;else r=`${c}use seu diagnóstico como filtro. A próxima ação deve produzir uma evidência pequena, concreta e relacionada ao resultado que você definiu. Evite abrir novas frentes antes de concluir essa ação.`;setReply(r)};
 const reset=()=>{if(confirm("Isso apagará todos os seus projetos, históricos, missões, registros e progresso. Deseja realmente começar novamente?")){localStorage.removeItem(KEY);setStore(blank);setLogin(false);nav("home")}};
 if(!store.user||login)return <Onboarding existing={!!store.user} name={name} setName={setName} password={password} setPassword={setPassword} onCancel={()=>setLogin(false)} onSubmit={()=>{if(!name.trim()||!password.trim())return;setStoreSafe({...store,user:{name:name.trim(),password}});setLogin(false);nav("home")}}/>;
 const filtered=store.projects.filter(p=>(filter==="Todos"||p.status===filter)&&p.title.toLowerCase().includes(query.toLowerCase()));
 return <div className="app-shell"><aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><div className="brand-mark"><Sparkles/></div><div><b>PROJETO DE VIDA</b><small>Instituto NeuroConsciência</small></div></div><div className="quote">“Você não precisa apenas de uma meta. Precisa de um caminho.”</div><nav><Nav icon={<Home/>} text="Início" active={view==="home"} onClick={()=>nav("home")}/><Nav icon={<LayoutGrid/>} text="Meus projetos" active={view==="projects"} onClick={()=>nav("projects")}/><Nav icon={<Plus/>} text="Novo objetivo" active={false} accent onClick={newGoal}/><Nav icon={<MessageCircle/>} text="Mentor de IA" active={view==="mentor"} onClick={()=>nav("mentor")}/><Nav icon={<BarChart3/>} text="Minha evolução" active={view==="evolution"} onClick={()=>nav("evolution")}/></nav><div className="side-bottom"><Nav icon={<Settings/>} text="Configurações" active={view==="settings"} onClick={()=>nav("settings")}/><button className="logout" onClick={()=>setLogin(true)}><LogOut/> Sair</button></div></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu/></button><span className="breadcrumb">{view==="home"?"Visão geral":view==="new"?"Nova jornada":view==="projects"?"Meus projetos":view==="project"?project?.title||"Projeto":view==="mentor"?"Mentor contextual":view==="evolution"?"Minha evolução":"Configurações"}</span><div className="user"><span>{store.user.name}</span><div>{store.user.name[0].toUpperCase()}</div></div></header><div className="content">
 {view==="home"&&<HomeView name={store.user.name} projects={store.projects} onNew={newGoal} onOpen={open} onAll={()=>nav("projects")}/>} 
 {view==="projects"&&<Projects projects={filtered} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} onNew={newGoal} onOpen={open}/>} 
 {view==="new"&&<Wizard step={wizard} setStep={setWizard} goal={goal} setGoal={setGoal} desc={desc} setDesc={setDesc} answers={answers} setAnswers={setAnswers} deadline={deadline} setDeadline={setDeadline} onBack={()=>wizard===1?nav("home"):setWizard(wizard-1)} onNext={()=>setWizard(wizard+1)} onCreate={create}/>} 
 {view==="project"&&project&&<ProjectView project={project} openStage={openStage} setOpenStage={setOpenStage} onToggle={toggleStage} onDuplicate={duplicate} onDelete={remove} onMentor={()=>nav("mentor")} onBack={()=>nav("projects")}/>} 
 {view==="mentor"&&<Mentor project={project} text={mentor} setText={setMentor} reply={reply} onAsk={mentorAsk}/>} 
 {view==="evolution"&&<Evolution projects={store.projects} completed={completed}/>} 
 {view==="settings"&&<SettingsView name={store.user.name} onReset={reset} onLogin={()=>setLogin(true)}/>} 
 </div><footer>© Instituto NeuroConsciência de Desenvolvimento Humano · Criador Jöweslëy</footer></main></div>;
}
function Nav({icon,text,active,accent,onClick}:{icon:any;text:string;active:boolean;accent?:boolean;onClick:()=>void}){return <button className={`nav ${active?"active":""} ${accent?"accent":""}`} onClick={onClick}>{icon}<span>{text}</span></button>}
function Onboarding({existing,name,setName,password,setPassword,onSubmit,onCancel}:any){return <div className="onboarding"><div className="onboarding-orb orb1"/><div className="onboarding-orb orb2"/><div className="welcome"><div className="welcome-mark"><Sparkles/></div><span className="eyebrow">INSTITUTO NEUROCONSCIÊNCIA</span><h1>{existing?"Bem-vindo de volta.":<>Sua vida.<br/><em>Seu caminho.</em><br/>Sua próxima ação.</>}</h1><p>{existing?"Continue seus projetos exatamente de onde parou.":"Do objetivo à execução. Da intenção à transformação."}</p><div className="onboard-form"><label>Seu nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Como podemos chamar você?" autoFocus/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Crie uma senha neste dispositivo"/></label><button className="primary wide" onClick={onSubmit}>{existing?"Continuar meu projeto":"Começar meu Projeto de Vida"}<ArrowRight/></button>{existing&&<button className="link" onClick={onCancel}>Voltar</button>}</div><div className="method"><span>OBJETIVO</span><i>→</i><span>INVESTIGAÇÃO</span><i>→</i><span>ESTRATÉGIA</span><i>→</i><span>EXECUÇÃO</span></div></div></div>}
function HomeView({name,projects,onNew,onOpen,onAll}:any){const active=projects.filter((p:Project)=>p.status==="Em andamento");return <section><div className="hero"><div><span className="eyebrow">PAINEL PESSOAL</span><h1>Olá, {name}.</h1><p>O que você deseja transformar em realidade?</p></div><button className="primary" onClick={onNew}><Plus/> Novo objetivo</button></div><div className="metrics"><Metric icon={<Target/>} label="Projetos" value={projects.length}/><Metric icon={<Zap/>} label="Em andamento" value={active.length}/><Metric icon={<CheckCircle2/>} label="Missões realizadas" value={projects.reduce((n:number,p:Project)=>n+p.logs.filter(l=>l.result==="concluída").length,0)}/></div><div className="section-title"><div><span className="eyebrow">SEU CAMINHO</span><h2>Meus projetos</h2></div>{projects.length>3&&<button className="ghost" onClick={onAll}>Ver todos <ArrowRight/></button>}</div>{projects.length?<div className="cards">{projects.slice(-3).reverse().map((p:Project)=><ProjectCard key={p.id} p={p} onOpen={onOpen}/>)}</div>:<Empty onNew={onNew}/>}<div className="dark-callout"><Lightbulb/><div><b>Menos confusão. Mais clareza. Uma ação de cada vez.</b><span>O Projeto de Vida transforma intenção em uma sequência concreta de decisões, execução e revisão.</span></div></div></section>}
function Metric({icon,label,value}:any){return <div className="metric"><div>{icon}</div><section><small>{label}</small><strong>{value}</strong></section></div>}
function Empty({onNew}:any){return <div className="empty"><div className="empty-mark"><Target/></div><h3>Seu primeiro projeto começa com uma decisão.</h3><p>Conte o que você deseja realizar. O sistema vai investigar seu contexto e transformar isso em um caminho executável.</p><button className="primary" onClick={onNew}><Plus/> Criar meu primeiro objetivo</button></div>}
function ProjectCard({p,onOpen}:any){const pr=progress(p);return <article className="card"><div className="card-head"><span className={`badge ${p.status==="Concluído"?"green":""}`}>{p.status}</span><MoreHorizontal/></div><div className="card-symbol"><Target/></div><h3>{p.title}</h3><p>{p.description||"Jornada personalizada para transformar este objetivo em ação."}</p><div className="bar-label"><span>Progresso</span><b>{pr}%</b></div><div className="bar"><i style={{width:`${pr}%`}}/></div><div className="card-meta"><span><Clock3/> {p.deadline}</span><span>{p.stages.filter(s=>s.done).length}/{p.stages.length} etapas</span></div><button className="card-btn" onClick={()=>onOpen(p)}>Continuar <ArrowRight/></button><button className="study" onClick={()=>onOpen(p)}>Estudar novamente</button></article>}
function Projects({projects,query,setQuery,filter,setFilter,onNew,onOpen}:any){return <section><div className="page-head"><div><span className="eyebrow">ARQUIVO PESSOAL</span><h1>Meus projetos</h1><p>Cada objetivo permanece independente, com seu próprio diagnóstico, plano e histórico.</p></div><button className="primary" onClick={onNew}><Plus/> Novo objetivo</button></div><div className="filters"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar objetivo..."/></div>{["Todos","Em andamento","Concluído","Pausado"].map((f:any)=><button className={filter===f?"selected":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div>{projects.length?<div className="cards">{projects.map((p:Project)=><ProjectCard key={p.id} p={p} onOpen={onOpen}/>)}</div>:<Empty onNew={onNew}/>}</section>}
function Wizard({step,setStep,goal,setGoal,desc,setDesc,answers,setAnswers,deadline,setDeadline,onBack,onNext,onCreate}:any){const qs=questions(goal);const valid=step===1?goal.trim().length>4:step===2?qs.every((_:string,i:number)=>answers[areas[i]]?.trim()):true;return <section className="journey"><div className="journey-top"><button className="back" onClick={onBack}><ChevronLeft/> Voltar</button><div className="steps">{[1,2,3,4].map((n)=><span className={n<=step?"on":""} key={n}>{n}</span>)}</div></div><div className="journey-panel"><span className="eyebrow">NOVA JORNADA · 0{step}/04</span>{step===1&&<><h1>Qual é o objetivo que você deseja realizar?</h1><p>Não escreva apenas “quero melhorar minha vida”. Explique o resultado que deseja alcançar e como imagina sua vida quando isso estiver realizado.</p><label>Seu objetivo<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Ex.: Quero criar uma fonte de renda com meu serviço de..." autoFocus/></label><label>Contexto adicional <textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="O que mais devemos saber sobre este objetivo? (opcional)"/></label></>}{step===2&&<><h1>Vamos investigar antes de planejar.</h1><p>As perguntas abaixo foram adaptadas ao seu objetivo. Responda com honestidade: suas respostas são a matéria-prima da estratégia.</p><div className="questions">{qs.map((q:string,i:number)=><label key={q}><span>{q}</span><textarea value={answers[areas[i]]||""} onChange={e=>setAnswers({...answers,[areas[i]]:e.target.value})} placeholder="Escreva sua resposta..."/></label>)}</div></>}{step===3&&<><h1>Em quanto tempo você deseja trabalhar para realizar esse objetivo?</h1><p>O prazo muda a cadência. O sistema vai adaptar a quantidade e a progressão das etapas sem misturar este projeto com outros.</p><div className="deadline-options">{deadlines.map(d=><button className={deadline===d?"chosen":""} onClick={()=>setDeadline(d)} key={d}><Clock3/><b>{d}</b><small>{d==="1 semana"?"7 etapas":d==="1 mês"?"4 semanas":d==="1 ano"?"12 meses":`${d.replace(" meses","")} meses`}</small></button>)}</div></>}{step===4&&<><div className="ready"><div><Check/></div><span className="eyebrow">JORNADA PRONTA</span><h1>Agora vamos transformar clareza em execução.</h1><p>Seu objetivo, investigação e prazo serão usados para construir um plano progressivo de <b>{periods(deadline).length} etapas</b>.</p></div><div className="summary"><div><small>OBJETIVO</small><b>{goal}</b></div><div><small>PRAZO</small><b>{deadline}</b></div><div><small>ETAPAS</small><b>{periods(deadline).length}</b></div></div></>}{step<4?<button className="primary next" disabled={!valid} onClick={onNext}>Continuar <ArrowRight/></button>:<button className="primary next" onClick={onCreate}>Construir meu plano <Sparkles/></button>}</div></section>}
function ProjectView({project,openStage,setOpenStage,onToggle,onDuplicate,onDelete,onMentor,onBack}:any){const pr=progress(project);return <section><div className="project-head"><button className="back" onClick={onBack}><ChevronLeft/> Meus projetos</button><div className="project-actions"><button className="ghost" onClick={onDuplicate}><Copy/> Nova jornada</button><button className="danger" onClick={onDelete}><Trash2/></button></div><span className="eyebrow">{project.status} · {project.deadline}</span><h1>{project.title}</h1><p>{project.description||"Uma jornada construída a partir do seu contexto e do resultado que você definiu."}</p><div className="bigbar"><div><span>Progresso geral</span><b>{pr}%</b></div><div className="bar"><i style={{width:`${pr}%`}}/></div><small>{project.stages.filter((s:Stage)=>s.done).length} de {project.stages.length} etapas concluídas · Última atividade {project.lastActivity}</small></div></div><div className="workspace"><div className="stage-list">{project.stages.map((s:Stage,i:number)=><article className={`stage ${openStage===i?"expanded":""} ${s.done?"completed":""}`} key={s.id}><button className="stage-header" onClick={()=>setOpenStage(i)}><div className="stage-number">{s.done?<Check/>:String(i+1).padStart(2,"0")}</div><div><small>{s.period}</small><h2>{s.objective}</h2></div><span>{openStage===i?<X/>:<ArrowRight/>}</span></button>{openStage===i&&<div className="stage-body"><Block title="OBJETIVO DA ETAPA"><p>{s.objective}</p></Block><Block title="POR QUE ISSO IMPORTA"><p>{s.why}</p></Block><Block title="PLANO DE EXECUÇÃO"><ol>{s.plan.map(x=><li key={x}>{x}</li>)}</ol></Block><Block title="EXERCÍCIO"><div className="exercise"><BookOpen/><p>{s.exercise}</p></div></Block><Block title="MISSÃO DE IMPLEMENTAÇÃO"><div className="mission"><div><Zap/><p>{s.mission}</p></div><button className={s.done?"done-btn":"primary"} onClick={onToggle}>{s.done?<><Check/> Concluída</>:<>Concluir missão <ArrowRight/></>}</button></div></Block><Block title="INDICADOR"><p>{s.indicator}</p></Block><Block title="PRÓXIMO PASSO"><p>{s.next}</p></Block></div>}</article>)}</div><aside className="project-side"><div className="mentor-mini"><div><Sparkles/></div><span className="eyebrow">MENTOR DO PROJETO</span><h3>Qual é sua próxima ação?</h3><p>Converse sobre atrasos, obstáculos, prioridade ou mudanças no objetivo.</p><button className="primary" onClick={onMentor}>Abrir mentor <ArrowRight/></button></div><div className="side-panel"><span>INVESTIGAÇÃO</span>{Object.entries(project.answers).map(([k,v])=><div key={k}><b>{k}</b><p>{v||"—"}</p></div>)}</div><div className="side-panel"><span>HISTÓRICO</span>{project.logs.slice(-5).reverse().map((l:Log,i:number)=><div className="history" key={i}><b>{l.date}</b><p>{l.stage} · {l.result}</p></div>)}{!project.logs.length&&<p>Nenhum registro ainda. Sua primeira missão cria o histórico.</p>}</div></aside></div></section>}
function Block({title,children}:any){return <section className="block"><span>{title}</span>{children}</section>}
function Mentor({project,text,setText,reply,onAsk}:any){return <section className="mentor-page"><div className="page-head"><div><span className="eyebrow">MENTOR CONTEXTUAL</span><h1>Mentor do meu projeto</h1><p>{project?`Contexto ativo: ${project.title}. As respostas consideram sua etapa atual e histórico.`:"Selecione um projeto para conversar com contexto."}</p></div></div><div className="chat"><div className="chat-msg bot"><div className="chat-avatar"><Sparkles/></div><div><b>Mentor do Projeto</b><p>{project?`Estou acompanhando “${project.title}”. Me diga o que está acontecendo e vamos encontrar a próxima ação executável.`:"Abra um projeto para que eu possa usar o contexto correto."}</p></div></div>{reply&&<div className="chat-msg bot"><div className="chat-avatar"><Sparkles/></div><div><b>Mentor</b><p>{reply}</p></div></div>}<div className="suggestions">{["Estou atrasado. O que faço?","O que devo priorizar hoje?","Estou pensando em desistir.","Meu objetivo mudou."].map(x=><button onClick={()=>setText(x)} key={x}>{x}</button>)}</div><div className="chat-input"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Conte o que está acontecendo..."/><button className="primary" onClick={onAsk}><ArrowRight/></button></div></div></section>}
function Evolution({projects,completed}:any){const total=projects.length;const done=projects.filter((p:Project)=>p.status==="Concluído").length;const avg=total?Math.round(projects.reduce((n:number,p:Project)=>n+progress(p),0)/total):0;return <section><div className="page-head"><div><span className="eyebrow">VISÃO DE LONGO PRAZO</span><h1>Minha evolução</h1><p>Veja sua trajetória sem misturar os contextos de cada projeto.</p></div></div><div className="evo-grid"><Metric icon={<Target/>} label="Objetivos trabalhados" value={total}/><Metric icon={<CheckCircle2/>} label="Projetos concluídos" value={done}/><Metric icon={<Zap/>} label="Missões realizadas" value={completed}/><Metric icon={<BarChart3/>} label="Evolução média" value={`${avg}%`}/></div><div className="evo-panel"><div className="panel-title"><div><span className="eyebrow">SEU MOVIMENTO</span><h2>Projetos e progresso</h2></div><Trophy/></div>{projects.length?projects.map((p:Project)=><div className="evo-row" key={p.id}><div><b>{p.title}</b><small>{p.deadline} · {p.status}</small></div><div className="bar"><i style={{width:`${progress(p)}%`}}/></div><strong>{progress(p)}%</strong></div>):<div className="empty small"><p>Crie seu primeiro objetivo para começar a registrar evolução.</p></div>}</div></section>}
function SettingsView({name,onReset,onLogin}:any){return <section className="settings-page"><div className="page-head"><div><span className="eyebrow">CONTROLE</span><h1>Configurações</h1><p>Preferências e segurança dos seus dados locais.</p></div></div><div className="settings-card"><div className="setting"><div><b>Perfil</b><span>Seu nome aparece nas orientações importantes.</span></div><strong>{name}</strong></div><div className="setting"><div><b>Armazenamento</b><span>Projetos e registros são mantidos localmente neste dispositivo.</span></div><strong>Local</strong></div><div className="setting danger-setting"><div><b>Reiniciar aplicativo</b><span>Apaga todos os projetos, históricos, missões, registros e progresso.</span></div><button className="danger" onClick={onReset}><RotateCcw/> Reiniciar</button></div><button className="ghost" onClick={onLogin}><LogOut/> Entrar com outro perfil</button></div></section>}
